### ISSUE TITLE
try using kit types

### ISSUE THREAD

**Issue by userquin** [userquin/vite-pwa-sveltekit-integration#7]
@benmccann is there some dts we can use from kit side here https://github.com/userquin/vite-pwa-sveltekit-integration/blob/main/src/types.ts#L3?

we should check if latest kit changes are ok in the types

**Comment by benmccann** [comment]
SvelteKit does distribute types

**Comment by userquin** [comment]
closing this since  we'll also need to change the config module logic if something changed in kit internals
