### ISSUE TITLE
Please provide a minimal example

### ISSUE THREAD

**Issue by homerjam** [userquin/vite-pwa-sveltekit-integration#81]
Hello,

This appears to be a fantastic and helpful module but I'm having a hard time piecing everything together - the docs jump around a little and seem aimed at advanced usage.

My past experience with PWAs was with Nuxt 2, there was a module which "just worked" - would it be possible to provide a very minimal example using a generated service worker and an aggressive caching strategy?

Ideally I just want to hit install and have everything downloaded so if I disconnect the wifi and refresh the site works.

Thanks!

**Comment by userquin** [comment]
@homerjam you can use `@vite-pwa/create-pwa` cli: https://vite-pwa-org.netlify.app/guide/scaffolding.html
